config/routes.rb
Tamagotchi::Application.routes.draw do
  resources(:avatars)

  
  root :to => 'application#index'
  

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  attr_accessible :energy, :name, :strength, :tag
  validates :tag, inclusion: {in: ["cat", "dog", "sheep"]}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def index
  end  
  
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  
  def index
    @avatars = Avatar.all
  end
  
  def show
    @avatar = Avatar.find(params[:id])
  end
  
  def new
    @avatar = Avatar.new
  end
  
  def edit
    @avatar = Avatar.find(params[:id])
  end

  def create
    avatar = Avatar.create(params[:avatar])
    redirect_to avatar_path(avatar)
  end
  
  def update
    avatar = Avatar.find(params[:id])
    avatar.update_attributes(params[:avatar])
    redirect_to avatar_path(avatar)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/views/application/index.html.erb
<h1>Bienvenue Sur Mayrargotchi</h1>
<h2><%= link_to "YOUR AVATARS", avatars_path %></h2>

app/views/application/welcome.html.erb
<h2>Hey <%= @name %></h2>	

app/views/avatars/_form.html.erb
<h2>Mon formulaire</h2>

<%= form_for(@avatar) do |f| %>

	<%= f.label(:name) %>
	<%= f.text_field :name %>
	
	<%= f.label(:energy) %>
	<%= f.select :energy, (1..10).to_a %>
	
	<%= f.label(:strength) %>
	<%= f.select :strength, (1..100).to_a %>
	
	<%= f.label(:tag) %>
	<%= f.select :tag, ["cat", "dog", "sheep"] %>
	
	<%= f.submit "CREATE"%>
	
<% end %>

app/views/avatars/edit.html.erb
<h1>MODIFIE CET AVATAR</h1>

<%= render "form" %>

app/views/avatars/index.html.erb
<h1>Voici tes avatars</h1>
<%= link_to "HOME", root_path %>

<ul>	
<% @avatars.each do |avatar| %>
	<li>
		<%= image_tag "#{avatar.tag}.png", class: "pet_pic"%>
		<%= avatar.name %>
		| Energy : <%= "*" * avatar.energy %>
		| Strength : <%= "+" * (avatar.strength / 10) %>
		
		<%= link_to "SHOW", avatar_path(avatar) %>
		<%= link_to "EDIT", edit_avatar_path(avatar) %>
	
	</li>
<% end %>
</ul>

app/views/avatars/new.html.erb
<h1>CREE UN NOUVEL AVATAR</h1>

<%= render "form" %>

app/views/avatars/show.html.erb
<%= image_tag "#{@avatar.tag}.png", class: "pet_pic"%>

<%= @avatar.name %>
| Energy : <%= "*" * @avatar.energy %>
| Strength : <%= "+" * (@avatar.strength / 10) %>

<%= link_to "LISTING", avatars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tamagotchi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  
  <%= yield %>


</body>
</html>